# Generated by Django 5.1.2 on 2025-07-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('food_type', models.CharField(max_length=50)),
                ('scaling_type', models.CharField(max_length=50)),
                ('ingredients', models.JSONField()),
                ('combine_with', models.JSONField()),
                ('not_combine_with', models.JSONField()),
                ('popularity', models.CharField(max_length=10)),
                ('availability', models.CharField(max_length=10)),
                ('halal', models.BooleanField()),
                ('fasting', models.BooleanField()),
                ('min_portion', models.IntegerField()),
                ('max_portion', models.IntegerField()),
                ('goals', models.ManyToManyField(to='mealplanner.goal')),
                ('periods', models.ManyToManyField(to='mealplanner.period')),
            ],
        ),
        migrations.CreateModel(
            name='Macronutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fats', models.FloatField()),
                ('calories', models.FloatField()),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='macros', to='mealplanner.food')),
            ],
        ),
        migrations.CreateModel(
            name='Micronutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iron', models.FloatField()),
                ('calcium', models.FloatField()),
                ('thiamine', models.FloatField()),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='micros', to='mealplanner.food')),
            ],
        ),
        migrations.CreateModel(
            name='DayMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('budget_level', models.CharField(max_length=20)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplanner.food')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplanner.period')),
            ],
        ),
    ]
