# Generated by Django 5.1.2 on 2025-07-31 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=35, null=True)),
                ('gym_house', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('profile_photo', models.ImageField(null=True, upload_to='')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('height', models.CharField(max_length=3, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10, null=True)),
                ('exercise_day', models.IntegerField(blank=True, null=True)),
                ('health_status', models.CharField(max_length=50, null=True)),
                ('exercise_type', models.CharField(max_length=20, null=True)),
                ('blood_type', models.CharField(max_length=20, null=True)),
                ('exercise_time_per_day', models.CharField(max_length=30, null=True)),
                ('fitness_goal', models.CharField(max_length=30, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('notificationTime', models.CharField(max_length=30, null=True)),
                ('enteringTime', models.CharField(max_length=30, null=True)),
                ('totalTimeSpendOnGym', models.CharField(max_length=30, null=True)),
                ('activityLevel', models.CharField(blank=True, choices=[('SL', 'Sedentary Level'), ('LA', 'Light Active'), ('MA', 'Moderately Active'), ('VA', 'Very Active')], default='LA', max_length=50, null=True)),
                ('qr_code', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
