# Generated by Django 5.1.2 on 2025-07-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMember', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='qr_code',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
