# Generated by Django 5.1.2 on 2025-07-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMember', '0002_alter_userprofile_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qr_code',
            field=models.TextField(null=True),
        ),
    ]
