# Generated by Django 5.1.2 on 2025-08-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMember', '0004_alter_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='start_gym',
            field=models.BooleanField(default=False),
        ),
    ]
