# Generated by Django 5.1.2 on 2025-03-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMember', '0005_userprofile_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gym_house',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
