# Generated by Django 5.1.2 on 2025-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMember', '0006_userprofile_gym_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exercise_time_per_day',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fitness_goal',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
