# Generated by Django 5.1.2 on 2025-08-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMember', '0006_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_fasting',
            field=models.BooleanField(null=True),
        ),
    ]
