# Generated by Django 5.1.2 on 2025-05-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMember', '0007_userprofile_exercise_time_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enteringTime',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notificationTime',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totalTimeSpendOnGym',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
