# Generated by Django 5.1.2 on 2025-05-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMember', '0008_userprofile_enteringtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activityLevel',
            field=models.CharField(blank=True, choices=[('SL', 'Sedentary Level'), ('LA', 'Light Active'), ('MA', 'Moderately Active'), ('VA', 'Very Active')], default='LA', max_length=10, null=True),
        ),
    ]
