# Generated by Django 5.1.2 on 2025-07-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMember', '0009_userprofile_activitylevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activityLevel',
            field=models.CharField(blank=True, choices=[('SL', 'Sedentary Level'), ('LA', 'Light Active'), ('MA', 'Moderately Active'), ('VA', 'Very Active')], default='LA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='health_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
